# Generated by Django 6.0.4 on 2026-05-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('rayban', 'Ray-Ban'), ('oakley', 'Oakley'), ('chilli', 'Chilli Beans'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('material', models.CharField(choices=[('acetato', 'Acetato'), ('metal', 'Metal'), ('titanio', 'Titânio'), ('policarbonato', 'Policabornato'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('formato', models.CharField(choices=[('redondo', 'Redondo'), ('quadrado', 'Quadrado'), ('gatinho', 'Gatinho'), ('aviador', 'Aviador'), ('retangular', 'Retangular'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('infantil', 'Infantil'), ('unissex', 'Unissex')], max_length=50)),
                ('medida_aro', models.IntegerField()),
                ('medida_ponte', models.IntegerField()),
                ('medida_haste', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
