# Generated by Django 6.0.4 on 2026-05-13 01:12

import backend.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oculos_snapshot', models.JSONField(help_text='Cópia de todos os dados do óculos no momento da reserva.', verbose_name='Snapshot do óculos')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('receita', models.FileField(help_text='Aceita JPG, PNG, PDF ou DOCX.', upload_to=backend.core.models.receita_upload_path, verbose_name='Receita do exame de vista')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('observacoes_admin', models.TextField(blank=True, verbose_name='Observações internas (admin)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.oculos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
