# Generated by Django 6.0.4 on 2026-05-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='oculos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
