# Generated by Django 6.0.4 on 2026-05-16 18:13

import backend.core.db_storage
import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_oculos_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('conteudo', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo no Banco',
                'db_table': 'arquivos_banco',
            },
        ),
        migrations.AddField(
            model_name='oculos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=backend.core.db_storage.DatabaseStorage(), upload_to='oculos/', verbose_name='Imagem do produto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='receita',
            field=models.FileField(help_text='Aceita JPG, PNG, PDF ou DOCX.', storage=backend.core.db_storage.DatabaseStorage(), upload_to=backend.core.models.receita_upload_path, verbose_name='Receita do exame de vista'),
        ),
    ]
