# Generated by Django 6.0.4 on 2026-05-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arquivobanco_oculos_imagem_alter_reserva_receita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('convenio', models.CharField(blank=True, help_text='Opcional', max_length=100, verbose_name='Convênio')),
                ('data_preferencia', models.DateField(verbose_name='Data de preferência')),
                ('periodo_preferido', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('qualquer', 'Qualquer horário')], default='qualquer', max_length=10, verbose_name='Período preferido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações / motivo do exame')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_confirmada', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora confirmada pela ótica')),
                ('observacoes_admin', models.TextField(blank=True, verbose_name='Observações internas (admin)')),
                ('retorno_cliente', models.TextField(blank=True, verbose_name='Mensagem de retorno ao cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento de Exame',
                'verbose_name_plural': 'Agendamentos de Exame',
                'ordering': ['-criado_em'],
            },
        ),
    ]
