# Generated by Django 6.0.4 on 2026-05-16 21:30

import backend.core.db_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exameagendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oculos',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='oculos',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='oculos',
            name='quantidade_estoque',
        ),
        migrations.CreateModel(
            name='OculosVarianteCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor da Armação/Lente')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Estoque desta cor')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço adicional')),
                ('oculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='core.oculos')),
            ],
            options={
                'verbose_name': 'Variante de Cor',
                'verbose_name_plural': 'Variantes de Cores',
                'unique_together': {('oculos', 'cor')},
            },
        ),
        migrations.CreateModel(
            name='OculosImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(storage=backend.core.db_storage.DatabaseStorage(), upload_to='oculos/', verbose_name='Imagem do produto')),
                ('e_principal', models.BooleanField(default=False, verbose_name='Imagem Principal da Cor')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.oculosvariantecor')),
            ],
            options={
                'verbose_name': 'Imagem da Variante',
                'verbose_name_plural': 'Imagens da Variante',
            },
        ),
    ]
