# Generated by Django 6.0.4 on 2026-05-17 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_oculos_cor_remove_oculos_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('lentes', models.JSONField(default=list)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.TextField(blank=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('oculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oculos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adicionado_em'],
                'unique_together': {('usuario', 'oculos', 'cor')},
            },
        ),
    ]
