# Generated by Django 6.0.4 on 2026-05-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itemcarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='oculos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='receita',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_visita',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario_visita',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_cliente',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='oculos_snapshot',
            field=models.JSONField(verbose_name='Snapshot dos óculos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone_whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('lentes', models.JSONField(default=list)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('oculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oculos')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.reserva')),
            ],
        ),
    ]
