# Generated by Django 6.0.4 on 2026-05-20 18:14

import backend.core.db_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_reserva_oculos_remove_reserva_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='receita',
            field=models.FileField(blank=True, null=True, storage=backend.core.db_storage.DatabaseStorage(), upload_to='receitas/', verbose_name='Receita médica'),
        ),
    ]
