name: Deploy para VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar na VPS e fazer deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/PI-PROJETO-OTICA
            git pull origin main
            
            # Backend
            source backend/venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            deactivate
            systemctl restart gunicorn
            
            # Frontend
            cd frontend
            npm install
            echo "NEXT_PUBLIC_API_URL=https://vizzootica.com/api" > .env.production
            npm run build
            pm2 restart nextjs